name: Notify Reviewers
on:
  pull_request:
    types:
      - review_requested
permissions:
  contents: read
jobs:
  notify-reviewers:
    name: Notify Reviewers
    uses: ScribeMD/slack-templates/.github/workflows/notify-reviewers.yaml@7e4cb7ce525cf4f29c6342375b1b0a7f8745f788 # 0.6.38
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_REVIEW_CHANNEL_ID: ${{ secrets.SLACK_REVIEW_CHANNEL_ID }}
